### ISSUE TITLE
RuntimeError while Training on GPU 

### ISSUE THREAD

**Issue by nikhil-garg** [neuromorphs/l2race#2]
Traceback (most recent call last):
  File "Train.py", line 321, in <module>
    time_to_accomplish = train_network(load_pretrained=False)
  File "Train.py", line 178, in train_network
    stack_output=False)
  File "/content/drive/.shortcut-targets-by-id/105/l2race/modeling/RNN0/utilis.py", line 272, in initialize_sequence
    self.h[0] = self.rnn_cell[0](input_t.squeeze(0), self.h[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/rnn.py", line 1046, in forward
    self.bias_ih, self.bias_hh,
RuntimeError: Tensor for argument #3 'input_bias' is on CPU, but expected it to be on GPU (while checking arguments for _thnn_fused_gru_cell_cuda)

**Comment by nikhil-garg** [comment]
Fixed by Mark Horeni in the dev branch
